apiVersion: v1
kind: Service
metadata:
  name: brute-force-cracker
spec:
  selector:
    app: brute-force-cracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
