apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-backend
  labels:
    app: orchestrator-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator-backend
  template:
    metadata:
      labels:
        app: orchestrator-backend
    spec:
      containers:
        - name: backend
          image: your-registry/orchestrator-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: orchestrator-config
            - secretRef:
                name: orchestrator-secrets
