apiVersion: v1
kind: Service
metadata:
  name: orchestrator-backend
spec:
  selector:
    app: orchestrator-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
