apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-frontend
  labels:
    app: orchestrator-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator-frontend
  template:
    metadata:
      labels:
        app: orchestrator-frontend
    spec:
      containers:
        - name: frontend
          image: your-registry/orchestrator-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: orchestrator-config
